// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using Parser4;
//
//    var aes = Aes.FromJson(jsonString);

namespace Parser4
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class Aes
    {
        public static string[] FromJson(string json) => JsonConvert.DeserializeObject<string[]>(json, Parser4.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this string[] self) => JsonConvert.SerializeObject(self, Parser4.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
